package company.pos.cashier;

import company.pos.admin.Charges;
import company.pos.database.MysqlConnect;
import company.pos.util.FrameUtil;
import company.pos.util.TableUtil;
import java.awt.Color;
import java.awt.Frame;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import net.sf.dynamicreports.jasper.builder.JasperReportBuilder;
import net.sf.dynamicreports.report.builder.DynamicReports;
import net.sf.dynamicreports.report.builder.column.Columns;
import net.sf.dynamicreports.report.builder.column.TextColumnBuilder;
import net.sf.dynamicreports.report.builder.component.Components;
import net.sf.dynamicreports.report.builder.datatype.DataTypes;
import net.sf.dynamicreports.report.builder.style.StyleBuilder;
import net.sf.dynamicreports.report.constant.HorizontalAlignment;
import net.sf.dynamicreports.report.constant.PageOrientation;
import net.sf.dynamicreports.report.constant.VerticalAlignment;
import net.sf.dynamicreports.report.exception.DRException;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Muhammad Hanif B
 */
public class PaymentPrintUI extends javax.swing.JPanel {

    /**
     * Creates new form Print
     * @param id
     * @param total
     */
    private final int id;
//    private final BigInteger total;
    private final String date;
    private final String tableNumber;
    
    private final Payment payment;
    
    private BigInteger paid;
    
//    BigInteger service = null;
    BigInteger tax = null;
    
    public PaymentPrintUI(int id, BigInteger total, String date, String tableNumber) {
        initComponents();
        this.id = id;
//        this.total = total;
        this.date = date;
        this.tableNumber = tableNumber;
        this.payment = new Payment();
//        this.addAdditionalCharges ();
        this.initOrderTable();        
    }

    private void initOrderTable () {
        tfTotal.setEditable(false);
        tfTax.setEditable(false);
//        tfService.setEditable(false);
        try {
            DefaultTableModel dtm = TableUtil.buildTableModel(payment.getPaymentDetail(this.date, this.tableNumber), true);
            tblPayment.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(PaymentUI.class.getName()).log(Level.SEVERE, null, ex);
        }          
    }
    
    private void addAdditionalCharges (String totalAll){
        try {            
            ResultSet rset = new Charges().getAllCharges();
            while (rset.next()) {
                if (rset.getString(2).toUpperCase().equals("SERVIS")) {
                    BigDecimal service = new BigDecimal(rset.getString(3));
                    BigDecimal totalDec = new BigDecimal(totalAll);                   
                    BigDecimal serviceTax = service.multiply(totalDec);
                    BigDecimal hundred = new BigDecimal(100);
                    BigInteger hundredInt = new BigInteger("100");
                    BigDecimal remain = serviceTax.remainder(hundred);
                    BigInteger roundTax = serviceTax.divide(hundred).toBigInteger();
                    roundTax = roundTax.multiply(hundredInt);                    
                    if ( remain.compareTo(BigDecimal.ZERO) > 0 ) {
                        if ( remain.compareTo(new BigDecimal(50)) > 0 ) {
                            roundTax = roundTax.add(hundredInt);
                        }
                    }
                    tfTax.setText(roundTax.toString());                
                    tax = roundTax;
                }
                
                /*if (rset.getString(2).toUpperCase().equals("SERVIS")) {
                    service = new BigInteger(rset.getString(3));
                    tfService.setText(service.toString());
                }*/                
            }            
            //tfTotal.setText(total.add(tax).add(service).toString());
            tfTotal.setText(new BigInteger(totalAll).add(tax).toString());
        } catch (SQLException ex) {
            Logger.getLogger(PaymentPrintUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayment = new javax.swing.JTable();
        btnPay = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfPaid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        tfTax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCalcTotal = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnMinimize.setBackground(new java.awt.Color(255, 255, 204));
        btnMinimize.setFocusPainted(false);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 204, 204));
        btnExit.setFocusPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cetak Pembayaran"));

        tblPayment.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Menu", "Harga", "Jumlah", "Total"
            }
        ));
        tblPayment.setRowHeight(30);
        jScrollPane1.setViewportView(tblPayment);

        btnPay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPay.setText("Bayar");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Back.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TOTAL :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("KEMBALI");

        tfPaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfPaid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("UANG YANG DIBAYARKAN :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Rp. ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Rp. ");

        tfTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tfTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfTax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("SERVIS :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Rp. ");

        btnCalcTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCalcTotal.setText("Hitung Total");
        btnCalcTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfTax)
                            .addComponent(tfPaid)
                            .addComponent(tfTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(btnCalcTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 555, Short.MAX_VALUE)
                        .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        FrameUtil.getCurrentFrame().setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        FrameUtil.changeUI(new PaymentUI(), (JFrame) SwingUtilities.getWindowAncestor(this));
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        paid = new BigInteger (tfPaid.getText());
        BigInteger totalwCharges = new BigInteger(tfTotal.getText());
        if (paid.compareTo(totalwCharges) < 0 ) {
            JOptionPane.showMessageDialog(this, "Jumlah uang yang dibayarkan kurang!"); 
        }
        else {
            showOrderPdf();
            boolean result = payment.pay(tableNumber, totalwCharges, paid);        
            if (result) {
                JOptionPane.showMessageDialog(this, "Berhasil!");            
                DefaultTableModel dtm = (DefaultTableModel) tblPayment.getModel();
                dtm.setRowCount(0);
                tblPayment.setModel(dtm);
                btnPay.setEnabled(false);
            }
            else { 
                JOptionPane.showMessageDialog(this, "Gagal!"); 
            }
        }        
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnCalcTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcTotalActionPerformed
        TableCellEditor editor = tblPayment.getCellEditor();
        if (editor != null) {
          editor.stopCellEditing();
        }
        this.calculateTotal();
    }//GEN-LAST:event_btnCalcTotalActionPerformed

    private boolean calculateTotal () {
        BigInteger totalAll = BigInteger.ZERO;
        int tabLen = tblPayment.getColumnCount();
        int rowCount = tblPayment.getRowCount();
        for (int i=0; i<rowCount; i++){
            if(tblPayment.getValueAt(i, 3) == null ||
                    tblPayment.getValueAt(i, 3).equals("")) { 
                tblPayment.setValueAt('1', i, 3);
            }

            String priceStr = tblPayment.getValueAt(i, 1).toString();
            String qtyStr = tblPayment.getValueAt(i, 3).toString();
            BigDecimal price = new BigDecimal(priceStr);
            BigDecimal qty = new BigDecimal(qtyStr);
            BigDecimal total = price.multiply(qty);
            totalAll = totalAll.add(total.toBigInteger());
            tblPayment.setValueAt(total.toBigInteger().toString(), i, tabLen-1);
        }
        System.out.println(totalAll + "************");
        tfTotal.setText("");
        this.addAdditionalCharges(totalAll.toString());
        return true;
    }
    
    private void showOrderPdf () {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date tgl = new Date();
        try {            
            BigInteger totalwCharges = new BigInteger(tfTotal.getText());
            MysqlConnect conn = MysqlConnect.getDbCon();
            JasperReportBuilder report = DynamicReports.report();
            report.setPageFormat(200, 1700, PageOrientation.PORTRAIT);
            try {
                StyleBuilder standarStyle = DynamicReports.stl.style()
                        .setFontSize(7)
                        .setHorizontalAlignment(HorizontalAlignment.CENTER)
                        .setVerticalAlignment(VerticalAlignment.MIDDLE);

                StyleBuilder titleStyle = DynamicReports.stl.style(standarStyle)
                        .setBackgroundColor(Color.LIGHT_GRAY);

                TextColumnBuilder<Integer> totalCol = Columns.column("Total", "total", DataTypes.integerType());

                ResultSet result = conn.query("select lower(pd.menu) as menu, sum(pd.jumlah) as jumlah, m.harga, sum(pd.jumlah) as humlah, sum(pd.jumlah*m.harga) as total from penjualan_detail pd\n" +
"left join menu m\n" +
"on pd.menu = m.nama left join penjualan p on p.penjualan_id = pd.penjualan_id where p.penjualan_tanggal='"+date+"' and p.meja='"+tableNumber+"' and p.ispaid = 0 group by menu", null);
                
                report                        
                        .setColumnTitleStyle(titleStyle)
                        .highlightDetailEvenRows()
                        .setSubtotalStyle(standarStyle)
                        .columns(
                                Columns.column("Menu", "menu", DataTypes.stringType()).setStyle(standarStyle),
                                Columns.column("Jumlah", "jumlah", DataTypes.stringType()).setStyle(standarStyle),
                                Columns.column("Harga", "harga", DataTypes.stringType()).setStyle(standarStyle),
                                totalCol.setStyle(standarStyle)
                        )
                        .title (
                                Components.horizontalList()
                                    .add(
                                        Components.image(getClass().getResource("/resources/icon.png")).setFixedDimension(49, 40),
                                        Components.text("\nJalan Raya Syeikh Nawawi\nPasar Ceplak, Balaraja\nTangerang\n").setStyle(standarStyle)
                                    ),   
                                Components.text("Meja "+tableNumber).setStyle(standarStyle)
                        )
                        .pageFooter(Components.text("TERIMA KASIH ATAS KUNJUNGAN ANDA").setStyle(standarStyle))
                        .pageFooter(Components.text(dateFormat.format(tgl)).setStyle(standarStyle))
                        .subtotalsAtSummary(DynamicReports.sbt.sum(totalCol))
                        .summary(Components.text("\n"))
                        //.summary(Components.text("Pajak (10%) : Rp. "+tax).setStyle(standarStyle).setHorizontalAlignment(HorizontalAlignment.RIGHT))
                        .summary(Components.text("Biaya Servis : Rp. "+tax).setStyle(standarStyle).setHorizontalAlignment(HorizontalAlignment.RIGHT))
                        .summary(Components.text("Total : Rp. "+totalwCharges).setStyle(standarStyle).setHorizontalAlignment(HorizontalAlignment.RIGHT))
                        .summary(Components.text("Jumlah yang dibayar : Rp. "+paid).setStyle(standarStyle).setHorizontalAlignment(HorizontalAlignment.RIGHT))
                        .summary(Components.text("Kembalian : Rp. "+paid.subtract(totalwCharges)).setStyle(standarStyle).setHorizontalAlignment(HorizontalAlignment.RIGHT))
                        .setDataSource(result);
               
                //langsung print
                report.print(false);
                report.print(false);
                
                JasperViewer viewer = new JasperViewer(report.toJasperPrint(), false);
                viewer.setExtendedState(JFrame.MAXIMIZED_BOTH);
                viewer.setTitle("Cetak Pembayaran");
                viewer.setVisible(true);                
            } catch (SQLException ex) {
                Logger.getLogger(OrderUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (DRException ex) {
            Logger.getLogger(OrderUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcTotal;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblPayment;
    private javax.swing.JTextField tfPaid;
    private javax.swing.JTextField tfTax;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
