/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pembayaran.java
 *
 * Created on May 29, 2011, 2:46:48 AM
 */
package windu.pos.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import windu.pos.entity.Barang;
import windu.pos.entity.Pelanggan;
import windu.pos.entity.PenjualanBarang;
import windu.pos.util.NumberHelper;

/**
 *
 * @author WinduPurnomo
 */
public class Pembayaran extends javax.swing.JFrame {
    private Penjualan formPenjualan;
    private double pembelian;
    private double pembayaran;
    private double kembalian;
    
    public Pembayaran(Penjualan penjualan) {
        initComponents();
        this.formPenjualan = penjualan;
        
        txtPembelian.setText(NumberHelper.thousandSparator(penjualan.totalPembelian));
        
        KeyStroke keyEnter = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false);
        KeyStroke keyEsc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        
        panel.registerKeyboardAction(enterAction, keyEnter, JComponent.WHEN_IN_FOCUSED_WINDOW);
        panel.registerKeyboardAction(actionEsc, keyEsc, JComponent.WHEN_IN_FOCUSED_WINDOW);
        
        txtPembayaran.requestFocusInWindow();
    }
    
    ActionListener enterAction = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            enterEvent(e);
        }
    };
    
    ActionListener actionEsc = new ActionListener() {
        public void actionPerformed(ActionEvent actionEvent) {
            escEvent(actionEvent);
        }
    };
    
    private void escEvent(ActionEvent actionEvent) {
        formPenjualan.setEnabled(true);
        formPenjualan.setVisible(true);
        this.setVisible(false);
    }
    
    private void enterEvent(ActionEvent e){
        try{
            pembayaran = Double.parseDouble(txtPembayaran.getText());
            pembelian = formPenjualan.totalPembelian;
            kembalian = pembayaran - formPenjualan.totalPembelian;
            dataChange();
            if (kembalian < 0) {
                JOptionPane.showMessageDialog(this, "Uang yang dibayarkan kurang", "Warning", JOptionPane.WARNING_MESSAGE);
                txtPembayaran.setText("");
                txtPembayaran.requestFocusInWindow();
            }else{
                lblKembalian.setText(String.valueOf(kembalian));
                formPenjualan.kembalian = kembalian;
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Hanya boleh angka", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void dataChange(){
        List<PenjualanBarang> listPenjBrg = new ArrayList<PenjualanBarang>();
        List<Barang> listBarang = new ArrayList<Barang>();
        listPenjBrg = formPenjualan.itemPenjualan;
        for (int i = 0; i < listPenjBrg.size(); i++) {
            int idBrg = listPenjBrg.get(i).getBarang().getId();
            Barang barang = new windu.pos.DaoImpl.Barang().selectById(idBrg);
            int jumJual = listPenjBrg.get(i).getJumlah();
            int jumAwal = barang.getJumlah();
            barang.setJumlah(jumAwal-jumJual);
            listBarang.add(barang);
        }
        new windu.pos.DaoImpl.Barang().updateByBatch(listBarang);
        
        //insert ke tabel penjualan
        windu.pos.entity.Penjualan penj = new windu.pos.entity.Penjualan();
        Pelanggan pelanggan = new Pelanggan();
        pelanggan.setId(1);
        
        penj.setTanggal(new Date());
        penj.setPelanggan(pelanggan);
        int idPenjualan = new windu.pos.DaoImpl.Penjualan().add(penj);
        penj.setIdPenjualan(idPenjualan);
        
        //insert ke tabel penjualanbarang
        for (int i = 0; i < listPenjBrg.size(); i++)
            listPenjBrg.get(i).setPenjualan(penj);
        new windu.pos.DaoImpl.PenjualanBarang().addByBatch(listPenjBrg);
        
        //kembali ke form penjualan
        formPenjualan.setLblKeterangan(NumberHelper.thousandSparator(pembelian),
                NumberHelper.thousandSparator(pembayaran),
                NumberHelper.thousandSparator(kembalian));
        formPenjualan.setEnabled(true);
        formPenjualan.setVisible(true);
        this.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPembelian = new javax.swing.JTextField();
        txtPembayaran = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblKembalian = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel1.setText("Total Pembelian");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel2.setText("Pembayaran");

        txtPembelian.setEditable(false);
        txtPembelian.setFont(new java.awt.Font("Calibri", 1, 14));

        txtPembayaran.setFont(new java.awt.Font("Calibri", 1, 14));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPembayaran)
                    .addComponent(txtPembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pembayaran");

        lblKembalian.setFont(new java.awt.Font("Calibri", 1, 14));
        lblKembalian.setForeground(new java.awt.Color(255, 0, 0));
        lblKembalian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKembalian.setText("-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel4.setText("OK [enter]   ;   Simpan[F1]  ;  Gagalkan [Esc]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKembalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-295)/2, (screenSize.height-182)/2, 295, 182);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtPembayaran;
    private javax.swing.JTextField txtPembelian;
    // End of variables declaration//GEN-END:variables
}
