/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Penjualan.java
 *
 * Created on May 27, 2011, 5:04:41 PM
 */
package windu.pos.ui;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import windu.pos.entity.Barang;
import windu.pos.entity.PenjualanBarang;
import windu.pos.util.NumberHelper;

/**
 *
 * @author WinduPurnomo
 */
public class Penjualan extends javax.swing.JFrame {
    
    private DefaultTableModel dtm;
    public List<PenjualanBarang> itemPenjualan = new ArrayList<PenjualanBarang>();
    List<Barang> listBarang = new windu.pos.DaoImpl.Barang().selectAll();
    public double kembalian;
    public double totalPembelian;
    
    /** Creates new form Penjualan */
    public Penjualan() {
        initComponents();
        tblPenjualan.getTableHeader().setFont( new Font("Calibri" , Font.BOLD, 18 ));
        
        KeyStroke keyF1 = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0, false);
        KeyStroke keyF2 = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0, false);
        KeyStroke keyEsc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        
        panel.registerKeyboardAction(actionF1, keyF1, JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        tblPenjualan.registerKeyboardAction(actionF2, keyF2, JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        panel.registerKeyboardAction(actionEsc, keyEsc, JComponent.WHEN_IN_FOCUSED_WINDOW);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }
    
    public void createTable(){
        String tblItem[][] = new String[itemPenjualan.size()][5];
        totalPembelian = 0;
        for (int i = 0; i < itemPenjualan.size(); i++) {
            Barang b = new Barang();
            b = itemPenjualan.get(i).getBarang();
            double harga = b.getHargaJual();
            int jumlah = itemPenjualan.get(i).getJumlah();
            double subtotal = harga * jumlah;
            tblItem[i][0] = b.getNama();
            tblItem[i][1] = NumberHelper.thousandSparator(harga);
            tblItem[i][2] = String.valueOf(jumlah);
            tblItem[i][3] = "";
            tblItem[i][4] = NumberHelper.thousandSparator(harga * jumlah);
            totalPembelian += subtotal;
        }
        lblTotal.setText("Rp "+NumberHelper.thousandSparator(totalPembelian));
        
        String [] title = new String [] {"Nama", "Harga", "Jumlah", "Diskon", "Total"};
        dtm = new DefaultTableModel(tblItem, title);
        tblPenjualan.setModel(dtm);
    }
    
    ActionListener actionF1 = new ActionListener() {
        public void actionPerformed(ActionEvent actionEvent) {
            myEvent(actionEvent);
        }
    };
    
    ActionListener actionF2 = new ActionListener() {
        public void actionPerformed(ActionEvent actionEvent) {
            f2Event(actionEvent);
        }
    };
    
    ActionListener actionEsc = new ActionListener() {
        public void actionPerformed(ActionEvent actionEvent) {
            escEvent(actionEvent);
        }
    };
    
    private void myEvent(ActionEvent actionEvent) {
        this.setEnabled(false);
        new PilihBarang(this).setVisible(true);
    }
    
    private void f2Event(ActionEvent actionEvent) {
        this.setEnabled(false);
        syncTabel();
        new Pembayaran(this).setVisible(true);
    }
    
    private void escEvent(ActionEvent actionEvent) {
        new Home().setVisible(true);
        this.setVisible(false);
    }
    
    
    public void setLblKeterangan(String pembelian, String pembayaran, String kembalian){
        String rp = "Rp ";
        lblTotalPembelian.setText(rp+pembelian);
        lblPembayaran.setText(rp+pembayaran);
        lblKembalian.setText(rp+kembalian);
        lblKembalian2.setText(rp+kembalian);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblKembalian = new javax.swing.JLabel();
        lblPembayaran = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalPembelian = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblKembalian2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Penjualan");
        setUndecorated(true);

        panel.setBackground(new java.awt.Color(204, 204, 0));
        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel.setForeground(new java.awt.Color(204, 204, 0));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("Rp 0");

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 0));

        tblPenjualan.setFont(new java.awt.Font("Calibri", 1, 18));
        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Jumlah", "Harga Satuan", "Diskon", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblPenjualan);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel4.setText("Pilih Barang [F1]   ;   Pembayaran[F2]");

        jLabel1.setText("Kembalian");

        lblKembalian.setFont(new java.awt.Font("Calibri", 1, 18));
        lblKembalian.setForeground(new java.awt.Color(255, 0, 0));
        lblKembalian.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKembalian.setText("Rp 0");

        lblPembayaran.setFont(new java.awt.Font("Calibri", 1, 18));
        lblPembayaran.setForeground(new java.awt.Color(255, 0, 0));
        lblPembayaran.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPembayaran.setText("Rp 0");

        jLabel5.setText("Pembayaran");

        lblTotalPembelian.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTotalPembelian.setForeground(new java.awt.Color(255, 0, 0));
        lblTotalPembelian.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalPembelian.setText("Rp 0");

        jLabel6.setText("Total Pembelian");

        lblKembalian2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblKembalian2.setForeground(new java.awt.Color(255, 0, 0));
        lblKembalian2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKembalian2.setText("Rp 0");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                        .addGap(520, 520, 520)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalPembelian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(lblKembalian2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKembalian2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKembalian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPembelian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(462, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1242)/2, (screenSize.height-491)/2, 1242, 491);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Penjualan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JLabel lblKembalian2;
    private javax.swing.JLabel lblPembayaran;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalPembelian;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tblPenjualan;
    // End of variables declaration//GEN-END:variables

    private void syncTabel() {
        for (int i = 0; i < tblPenjualan.getRowCount(); i++) {
            
        }
    }
}
